name: Achievements
version: '${project.version}'
main: cl.bgm.achievements.Achievements
authors: [ BGMP ]
description: Custom achievements plugin
commands:
  coordinates:
    usage: /coordinates
    description: Broadcasts your current coordinates.
    aliases: [coord, coords]
  statistics:
    usage: /statistics
    description: See your server stats.
    aliases: [stats]
